# Generated by Django 4.0.1 on 2022-01-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='auth',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
