# Generated by Django 4.0.1 on 2022-02-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_remove_book_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
