# Generated by Django 4.0.1 on 2022-02-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_book_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=1, max_length=1),
        ),
    ]
