# Generated by Django 4.0.1 on 2022-02-03 05:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_alter_book_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
